// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrqZaM2MSthhvfkCv2Kmgp3RSUZTtMDkA',
    appId: '1:101255694275:web:8b7d0e143472b8a6e41f76',
    messagingSenderId: '101255694275',
    projectId: 'doctorappointmentapp-efa88',
    authDomain: 'doctorappointmentapp-efa88.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-efa88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy3ciURfDiIGSBuBUsKiag5PuYiXkk9W0',
    appId: '1:101255694275:android:ec9b9ba90d38cec0e41f76',
    messagingSenderId: '101255694275',
    projectId: 'doctorappointmentapp-efa88',
    storageBucket: 'doctorappointmentapp-efa88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByYrfcnz8eOPgyS49hiSWYL1HMpM6HnKs',
    appId: '1:101255694275:ios:49ce91a87398163ee41f76',
    messagingSenderId: '101255694275',
    projectId: 'doctorappointmentapp-efa88',
    storageBucket: 'doctorappointmentapp-efa88.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentAppFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByYrfcnz8eOPgyS49hiSWYL1HMpM6HnKs',
    appId: '1:101255694275:ios:49ce91a87398163ee41f76',
    messagingSenderId: '101255694275',
    projectId: 'doctorappointmentapp-efa88',
    storageBucket: 'doctorappointmentapp-efa88.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentAppFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrqZaM2MSthhvfkCv2Kmgp3RSUZTtMDkA',
    appId: '1:101255694275:web:e9d075c794d7582de41f76',
    messagingSenderId: '101255694275',
    projectId: 'doctorappointmentapp-efa88',
    authDomain: 'doctorappointmentapp-efa88.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-efa88.firebasestorage.app',
  );
}
