// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbtL4D_lPVJ5_XicgyJvYYV4DDjgbdpsc',
    appId: '1:468384070343:web:c5f1f996d64fc9d4e1dce2',
    messagingSenderId: '468384070343',
    projectId: 'doctor-appointment-app-952fa',
    authDomain: 'doctor-appointment-app-952fa.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-952fa.firebasestorage.app',
    measurementId: 'G-GMK5X6VGTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj1KmM6cP-cLnSdafyecwlvOZ6-JctHLY',
    appId: '1:468384070343:android:1cf768ec086d572fe1dce2',
    messagingSenderId: '468384070343',
    projectId: 'doctor-appointment-app-952fa',
    storageBucket: 'doctor-appointment-app-952fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5zojtcDJd7bYdkVSipp508xJSWqOkC-E',
    appId: '1:468384070343:ios:4f906a6824baed85e1dce2',
    messagingSenderId: '468384070343',
    projectId: 'doctor-appointment-app-952fa',
    storageBucket: 'doctor-appointment-app-952fa.firebasestorage.app',
    iosClientId: '468384070343-hg46redgifcl5hq9el2f7i2qar79ufhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointmentAppFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5zojtcDJd7bYdkVSipp508xJSWqOkC-E',
    appId: '1:468384070343:ios:4f906a6824baed85e1dce2',
    messagingSenderId: '468384070343',
    projectId: 'doctor-appointment-app-952fa',
    storageBucket: 'doctor-appointment-app-952fa.firebasestorage.app',
    iosClientId: '468384070343-hg46redgifcl5hq9el2f7i2qar79ufhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointmentAppFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbtL4D_lPVJ5_XicgyJvYYV4DDjgbdpsc',
    appId: '1:468384070343:web:aec4a43af4a34d32e1dce2',
    messagingSenderId: '468384070343',
    projectId: 'doctor-appointment-app-952fa',
    authDomain: 'doctor-appointment-app-952fa.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-952fa.firebasestorage.app',
    measurementId: 'G-VT2NXM334S',
  );

}